[package]
name = "rust_actix_api"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = '4.4.0'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
